version: '3'

services:
  backend:
    build: backend
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://anastasiya:Anastasiya1@db:5432/chicken_counting
    ports:
      - "9032:9032"

    container_name: backend

  frontend:
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - "9031:9031"

    container_name: frontend

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=anastasiya
      - POSTGRES_PASSWORD=Anastasiya1
      - POSTGRES_DB=chicken_counting

  nvsmi:
    image: ubuntu:20.04
    runtime: nvidia
    environment:
     - NVIDIA_VISIBLE_DEVICES=ALL
    command: nvidia-smi
volumes:
  postgres_data:
